-- SQLite
-- CREATE TABLE OpenCV(
-- ID INTEGER PRIMARY KEY AUTOINCREMENT,
-- Encoding TEXT NOT NULL,
-- ImageID INTEGER NOT NULL,
-- FOREIGN KEY(ImageID) REFERENCES Image(ID)
-- );

SELECT * FROM RegUser;

DELETE FROM RegUser WHERE RealName = "";